package Forms;


import entity.player_entity;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import main.main;
import sqlConnection.SQLcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author MOHAMED
 */
public class Player extends javax.swing.JPanel {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public Player() {
        initComponents();
        conn = SQLcon.connecrb();
        show_player_entity();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel_player_id = new javax.swing.JLabel();
        jLabel_age = new javax.swing.JLabel();
        jLabel_fname = new javax.swing.JLabel();
        jLabel_lname = new javax.swing.JLabel();
        jLabel_player_national = new javax.swing.JLabel();
        jLabel_height = new javax.swing.JLabel();
        jLabel_club_id = new javax.swing.JLabel();
        jTextField_age = new javax.swing.JTextField();
        jTextField_fname = new javax.swing.JTextField();
        jTextField_lname = new javax.swing.JTextField();
        jTextField_height = new javax.swing.JTextField();
        jTextField_player_national = new javax.swing.JTextField();
        jTextField_player_id = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField_position = new javax.swing.JTextField();
        jLabel_position = new javax.swing.JLabel();
        jLabel_shirt_num = new javax.swing.JLabel();
        jLabel_preferred_foot = new javax.swing.JLabel();
        jTextField_shirt_num = new javax.swing.JTextField();
        jTextField_club_id = new javax.swing.JTextField();
        jTextField_preferred_foot = new javax.swing.JTextField();
        jLabel_salary = new javax.swing.JLabel();
        jTextField_salary = new javax.swing.JTextField();
        jButton_add1 = new javax.swing.JButton();
        jButton_update = new javax.swing.JButton();
        jButton_delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setBackground(new java.awt.Color(5, 117, 230));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/2.png"))); // NOI18N
        jLabel4.setText("Player Information ");
        jLabel4.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_player_id.setBackground(new java.awt.Color(5, 117, 230));
        jLabel_player_id.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_player_id.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_player_id.setText("Player ID");
        jLabel_player_id.setOpaque(true);

        jLabel_age.setBackground(new java.awt.Color(5, 117, 230));
        jLabel_age.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_age.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_age.setText("Age");
        jLabel_age.setOpaque(true);

        jLabel_fname.setBackground(new java.awt.Color(5, 117, 230));
        jLabel_fname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_fname.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_fname.setText("First Name");
        jLabel_fname.setOpaque(true);

        jLabel_lname.setBackground(new java.awt.Color(5, 117, 230));
        jLabel_lname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_lname.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_lname.setText("Last Name");
        jLabel_lname.setOpaque(true);

        jLabel_player_national.setBackground(new java.awt.Color(5, 117, 230));
        jLabel_player_national.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_player_national.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_player_national.setText("Nationality");
        jLabel_player_national.setOpaque(true);

        jLabel_height.setBackground(new java.awt.Color(5, 117, 230));
        jLabel_height.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_height.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_height.setText("Height");
        jLabel_height.setOpaque(true);

        jLabel_club_id.setBackground(new java.awt.Color(5, 117, 230));
        jLabel_club_id.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_club_id.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_club_id.setText("Club ID");
        jLabel_club_id.setOpaque(true);

        jTextField_fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_fnameActionPerformed(evt);
            }
        });

        jTextField7.setText("jTextField1");

        jLabel_position.setBackground(new java.awt.Color(5, 117, 230));
        jLabel_position.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_position.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_position.setText("Position ");
        jLabel_position.setOpaque(true);

        jLabel_shirt_num.setBackground(new java.awt.Color(5, 117, 230));
        jLabel_shirt_num.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_shirt_num.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_shirt_num.setText("Shirt Number");
        jLabel_shirt_num.setOpaque(true);

        jLabel_preferred_foot.setBackground(new java.awt.Color(5, 117, 230));
        jLabel_preferred_foot.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_preferred_foot.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_preferred_foot.setText("Preferred Foot");
        jLabel_preferred_foot.setOpaque(true);

        jLabel_salary.setBackground(new java.awt.Color(5, 117, 230));
        jLabel_salary.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_salary.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_salary.setText("Salary");
        jLabel_salary.setOpaque(true);

        jButton_add1.setBackground(java.awt.Color.green);
        jButton_add1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_add1.setForeground(new java.awt.Color(255, 255, 255));
        jButton_add1.setText("ADD");
        jButton_add1.setOpaque(true);
        jButton_add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_add1ActionPerformed(evt);
            }
        });

        jButton_update.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        jButton_update.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_update.setForeground(new java.awt.Color(255, 255, 255));
        jButton_update.setText("Update");
        jButton_update.setOpaque(true);
        jButton_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateActionPerformed(evt);
            }
        });

        jButton_delete.setBackground(java.awt.Color.red);
        jButton_delete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_delete.setForeground(new java.awt.Color(255, 255, 255));
        jButton_delete.setText("Delete");
        jButton_delete.setOpaque(true);
        jButton_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_preferred_foot)
                    .addComponent(jLabel_height)
                    .addComponent(jLabel_age)
                    .addComponent(jLabel_fname)
                    .addComponent(jLabel_player_id)
                    .addComponent(jLabel_salary))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_salary, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField_preferred_foot, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_position)
                            .addComponent(jLabel_club_id)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField_age, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_player_national))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_lname))
                    .addComponent(jTextField_player_id, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField_height, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_shirt_num)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField_shirt_num, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addComponent(jTextField_player_national, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_lname, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_club_id, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_position))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton_add1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_update, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jButton_delete, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(13, 13, 13))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(166, 166, 166)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(345, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_club_id)
                            .addComponent(jTextField_club_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_add1))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_lname)
                                    .addComponent(jTextField_fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_fname))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_player_national)
                                    .addComponent(jTextField_player_national, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_age)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jButton_update))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_player_id)
                            .addComponent(jTextField_player_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField_shirt_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton_delete))
                            .addComponent(jLabel_shirt_num)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_height, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_height)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_preferred_foot)
                                    .addComponent(jTextField_preferred_foot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_salary)
                                    .addComponent(jTextField_salary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel_position)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_position, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(122, 122, 122)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(78, Short.MAX_VALUE)))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "player_id", "fname", "lname", "age", "player_national", "height", "position", "preferred_foot", "club_id", "shirt_num", "salary"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_fnameActionPerformed

    private void jButton_add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_add1ActionPerformed
        // TODO add your handling code here:
//        String player_id_text = jTextField_player_id.getText();
//        int player_id = Integer.parseInt(player_id_text);
        String fname = jTextField_fname.getText();
        String lname = jTextField_lname.getText();
        String age_text = jTextField_age.getText();
        int age = Integer.parseInt(age_text);
        String player_national = jTextField_player_national.getText();
        String height_text = jTextField_height.getText();
        int height = Integer.parseInt(height_text);
        String position = jTextField_position.getText();
        String preferred_foot = jTextField_preferred_foot.getText();
        String club_id_text = jTextField_club_id.getText();
        int club_id = Integer.parseInt(club_id_text);
        String shirt_num_text = jTextField_shirt_num.getText();
        int shirt_num = Integer.parseInt(shirt_num_text);
        String salary_text = jTextField_salary.getText();
        int salary = Integer.parseInt(salary_text);
        String sqlquery = "INSERT INTO player (fname, lname, age, player_national, height, position, preferred_foot, club_id, shirt_num,salary) VALUES"
                + "('" + fname + "', '" + lname + "', " + age + ", '" + player_national + "', " + height + ", '" + position + "', '" + preferred_foot + "', " + club_id + "," + shirt_num + ", " + salary + ")";

        try {
            pst = conn.prepareStatement(sqlquery);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Record Added Successfully");
            show_player_entity();

//            jTextField_player_id.setText("");
            jTextField_fname.setText("");
            jTextField_lname.setText("");
            jTextField_age.setText("");
            jTextField_player_national.setText("");
            jTextField_height.setText("");
            jTextField_position.setText("");
            jTextField_preferred_foot.setText("");
            jTextField_club_id.setText("");
            jTextField_shirt_num.setText("");
            jTextField_salary.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        //
    }//GEN-LAST:event_jButton_add1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int r = jTable1.getSelectedRow();
        String click = jTable1.getModel().getValueAt(r, 0).toString();
        int id = Integer.parseInt(click);
        String sqlquery = "Select * from player where player_id=" + id;
        try {
            pst = conn.prepareStatement(sqlquery);
            rs = pst.executeQuery();
            if (rs.next()) {

                String player_id = rs.getString(1);
                jTextField_player_id.setText(player_id);

                String fname = rs.getString(2);
                jTextField_fname.setText(fname);

                String lname = rs.getString(3);
                jTextField_lname.setText(lname);

                String age = rs.getString(4);
                jTextField_age.setText(age);

                String player_national = rs.getString(5);
                jTextField_player_national.setText(player_national);

                String height = rs.getString(6);
                jTextField_height.setText(height);

                String position = rs.getString(7);
                jTextField_position.setText(position);

                String preferred_foot = rs.getString(8);
                jTextField_preferred_foot.setText(preferred_foot);

                String club_id = rs.getString(9);
                jTextField_club_id.setText(club_id);

                String shirt_num = rs.getString(10);
                jTextField_shirt_num.setText(shirt_num);

                String salary = rs.getString(11);
                jTextField_salary.setText(salary);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateActionPerformed
        String player_id_text = jTextField_player_id.getText();
        int player_id = Integer.parseInt(player_id_text);
        String fname = jTextField_fname.getText();
        String lname = jTextField_lname.getText();
        String age_text = jTextField_age.getText();
        int age = Integer.parseInt(age_text);
        String player_national = jTextField_player_national.getText();
        String height_text = jTextField_height.getText();
        int height = Integer.parseInt(height_text);
        String position = jTextField_position.getText();
        String preferred_foot = jTextField_preferred_foot.getText();
        String club_id_text = jTextField_club_id.getText();
        int club_id = Integer.parseInt(club_id_text);
        String shirt_num_text = jTextField_shirt_num.getText();
        int shirt_num = Integer.parseInt(shirt_num_text);
        String salary_text = jTextField_salary.getText();
        int salary = Integer.parseInt(salary_text);
        String sqlquery = "Update player SET player_id=?,fname=?,lname=?,age=?,player_national=?,height=?,position=?,preferred_foot=?,club_id=?,shirt_num=?,salary=? where player_id='" + player_id_text+"'";         // TODO add your handling code here:
        try {
            pst = conn.prepareStatement(sqlquery);
            pst.setInt(1, player_id);
            pst.setString(2, fname);
            pst.setString(3, lname);
            pst.setInt(4, age);
            pst.setString(5, player_national);
            pst.setInt(6, height);
            pst.setString(7, position);
            pst.setString(8, preferred_foot);
            pst.setInt(9, club_id);
            pst.setInt(10, shirt_num);
            pst.setInt(11, salary);
            pst.executeUpdate();
            show_player_entity();
            JOptionPane.showMessageDialog(null, "Record Update Successful");
            jTextField_player_id.setText("");
            jTextField_fname.setText("");
            jTextField_lname.setText("");
            jTextField_age.setText("");
            jTextField_player_national.setText("");
            jTextField_height.setText("");
            jTextField_position.setText("");
            jTextField_preferred_foot.setText("");
            jTextField_club_id.setText("");
            jTextField_shirt_num.setText("");
            jTextField_salary.setText("");
        }   catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            }  
    }//GEN-LAST:event_jButton_updateActionPerformed

    private void jButton_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteActionPerformed
        try{
            
            int row= jTable1.getSelectedRow();
            String value=(jTable1.getModel().getValueAt (row, 0).toString());
            String query="DELETE FROM player where player_id ="+value;
            PreparedStatement pst = conn.prepareStatement (query);
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount (0);
            show_player_entity();
            JOptionPane.showMessageDialog(null,"Deleted Successfully!");
            }
            catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            }           
    }//GEN-LAST:event_jButton_deleteActionPerformed

    public ArrayList<player_entity>playerlist(){
        ArrayList<player_entity> playerlist =new ArrayList<>();
        String sqlquery = "Select * from player where player.club_id=1";
        try {
             Statement st=conn.createStatement();
             rs=st.executeQuery(sqlquery);
             player_entity player_entity;
             while (rs.next()) {
                player_entity =new player_entity(rs.getInt("player_id"),rs.getString("fname"),rs.getString("lname"),rs.getInt("age"),rs.getString("player_national"),rs.getInt("height"),rs.getString("position"),rs.getString("preferred_foot"),rs.getInt("club_id"),rs.getInt("shirt_num"),rs.getInt("salary"));
                playerlist.add(player_entity);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return playerlist;
    }

  public void show_player_entity() {
        ArrayList<player_entity> list = playerlist();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        Object[] row = new Object [11];
    for (int i=0;i<list.size(); i++) {
    row [0]=list.get(i).getPlayer_id();
    row [1]=list.get(i).getFname();
    row [2]=list.get(i).getLname();
    row [3]=list.get(i).getAge();
    row [4]=list.get(i).getPlayer_national();
    row [5]=list.get(i).getHeight();
    row [6]=list.get(i).getPosition(); 
    row [7]=list.get(i).getPreferred_foot();
    row [8]=list.get(i).getClub_id(); 
    row [9]=list.get(i).getShirt_num();
    row [10]=list.get(i).getSalary();
    model.addRow(row);
}
  }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_add1;
    private javax.swing.JButton jButton_delete;
    private javax.swing.JButton jButton_update;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_age;
    private javax.swing.JLabel jLabel_club_id;
    private javax.swing.JLabel jLabel_fname;
    private javax.swing.JLabel jLabel_height;
    private javax.swing.JLabel jLabel_lname;
    private javax.swing.JLabel jLabel_player_id;
    private javax.swing.JLabel jLabel_player_national;
    private javax.swing.JLabel jLabel_position;
    private javax.swing.JLabel jLabel_preferred_foot;
    private javax.swing.JLabel jLabel_salary;
    private javax.swing.JLabel jLabel_shirt_num;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField_age;
    private javax.swing.JTextField jTextField_club_id;
    private javax.swing.JTextField jTextField_fname;
    private javax.swing.JTextField jTextField_height;
    private javax.swing.JTextField jTextField_lname;
    private javax.swing.JTextField jTextField_player_id;
    private javax.swing.JTextField jTextField_player_national;
    private javax.swing.JTextField jTextField_position;
    private javax.swing.JTextField jTextField_preferred_foot;
    private javax.swing.JTextField jTextField_salary;
    private javax.swing.JTextField jTextField_shirt_num;
    // End of variables declaration//GEN-END:variables
}
