/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package forms;

import entity.staff_entity;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import main.main;
import sqlConnection.SQLcon;

/**
 *
 * @author MOHAMED
 */
public class staff extends javax.swing.JPanel {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form staff
     */
    public staff() {
        initComponents();
        conn = SQLcon.connecrb();
//       populate_table();
        show_staff_entity();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_staff_id = new javax.swing.JLabel();
        jLabel_age = new javax.swing.JLabel();
        jLabel_coach_id = new javax.swing.JLabel();
        jLabel_name = new javax.swing.JLabel();
        jLabel_position = new javax.swing.JLabel();
        jTextField_age = new javax.swing.JTextField();
        jTextField_coach_id = new javax.swing.JTextField();
        jTextField_staff_id = new javax.swing.JTextField();
        jTextField_name = new javax.swing.JTextField();
        buttonGradient1_add = new swing.ButtonGradient();
        buttonGradient1_delete = new swing.ButtonGradient();
        buttonGradient1_update1 = new swing.ButtonGradient();
        jTextField_position = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_staff_id.setBackground(new java.awt.Color(5, 117, 230));
        jLabel_staff_id.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_staff_id.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_staff_id.setText("Staff ID");
        jLabel_staff_id.setOpaque(true);

        jLabel_age.setBackground(new java.awt.Color(5, 117, 230));
        jLabel_age.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_age.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_age.setText("Age");
        jLabel_age.setOpaque(true);

        jLabel_coach_id.setBackground(new java.awt.Color(5, 117, 230));
        jLabel_coach_id.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_coach_id.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_coach_id.setText("Coach ID");
        jLabel_coach_id.setOpaque(true);

        jLabel_name.setBackground(new java.awt.Color(5, 117, 230));
        jLabel_name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_name.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_name.setText("Name");
        jLabel_name.setOpaque(true);

        jLabel_position.setBackground(new java.awt.Color(5, 117, 230));
        jLabel_position.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_position.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_position.setText("Position");
        jLabel_position.setOpaque(true);

        jTextField_coach_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_coach_idActionPerformed(evt);
            }
        });

        jTextField_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nameActionPerformed(evt);
            }
        });

        buttonGradient1_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-add-48.png"))); // NOI18N
        buttonGradient1_add.setColor1(new java.awt.Color(255, 255, 255));
        buttonGradient1_add.setColor2(new java.awt.Color(255, 255, 255));
        buttonGradient1_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGradient1_addActionPerformed(evt);
            }
        });

        buttonGradient1_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-delete-48.png"))); // NOI18N
        buttonGradient1_delete.setText("buttonGradient1");
        buttonGradient1_delete.setColor1(new java.awt.Color(255, 255, 255));
        buttonGradient1_delete.setColor2(new java.awt.Color(255, 255, 255));
        buttonGradient1_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGradient1_deleteActionPerformed(evt);
            }
        });

        buttonGradient1_update1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-available-updates-50.png"))); // NOI18N
        buttonGradient1_update1.setText("buttonGradient1");
        buttonGradient1_update1.setColor1(new java.awt.Color(255, 255, 255));
        buttonGradient1_update1.setColor2(new java.awt.Color(255, 255, 255));
        buttonGradient1_update1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGradient1_update1ActionPerformed(evt);
            }
        });

        jTextField_position.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_positionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_staff_id)
                    .addComponent(jLabel_age)
                    .addComponent(jLabel_coach_id))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(buttonGradient1_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                        .addComponent(buttonGradient1_update1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField_staff_id, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                            .addComponent(jTextField_age, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_coach_id, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_position)
                            .addComponent(jLabel_name))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_position, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(jTextField_name)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(buttonGradient1_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel_age))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_staff_id)
                            .addComponent(jTextField_staff_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_name)
                            .addComponent(jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_position)
                            .addComponent(jTextField_position, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_coach_id)
                    .addComponent(jTextField_coach_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonGradient1_update1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonGradient1_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buttonGradient1_add, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "staff_id", "name", "age", "position", "coach_id"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel4.setBackground(new java.awt.Color(5, 117, 230));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Staff");
        jLabel4.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_coach_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_coach_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_coach_idActionPerformed

    private void jTextField_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nameActionPerformed

    private void buttonGradient1_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGradient1_addActionPerformed
        
        
//        String staff_id_text = jTextField_staff_id.getText();
//        int staff_id = Integer.parseInt(staff_id_text);
        
        String name = jTextField_name.getText();


        String age_text = jTextField_age.getText();
        int age = Integer.parseInt(age_text);

        String position = jTextField_position.getText();
        
        String coach_id_text = jTextField_coach_id.getText();
        int coach_id = Integer.parseInt(coach_id_text);
        

        String sqlquery = "INSERT INTO staff (name, age, position, coach_id) VALUES"
                + "('" + name + "', " + age + ", '" + position + "', "+ coach_id + ")";

        try {
            pst = conn.prepareStatement(sqlquery);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Record Added Successfully");
            //            populate_table();
            show_staff_entity();
//            jTextField_staff_id.setText("");
            jTextField_coach_id.setText("");
            jTextField_position.setText("");
            jTextField_age.setText("");
            jTextField_name.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        //        // TODO add your handling code here:
    }//GEN-LAST:event_buttonGradient1_addActionPerformed

    private void buttonGradient1_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGradient1_deleteActionPerformed
        try {

            int row = jTable1.getSelectedRow();
            String value = (jTable1.getModel().getValueAt(row, 0).toString());
            String query = "DELETE FROM staff where staff_id =" + value;
            PreparedStatement pst = conn.prepareStatement(query);
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
            show_staff_entity();
            JOptionPane.showMessageDialog(null, "Deleted Successfully!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }                  // TODO add your handling code here:
    }//GEN-LAST:event_buttonGradient1_deleteActionPerformed

    private void buttonGradient1_update1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGradient1_update1ActionPerformed
        String staff_id_text = jTextField_staff_id.getText();
        int staff_id = Integer.parseInt(staff_id_text);

        String name = jTextField_name.getText();

        String age_text = jTextField_age.getText();
        int age = Integer.parseInt(age_text);

        String position = jTextField_position.getText();
        
        String coach_id_text = jTextField_coach_id.getText();
        int coach_id = Integer.parseInt(coach_id_text);
        
        String sqlquery = "Update staff SET staff_id=?,name=?,age=?,position=?, coach_id where staff_id='" + staff_id_text + "'";         // TODO add your handling code here:
        try {
            pst = conn.prepareStatement(sqlquery);
            pst.setInt(1, staff_id);
            pst.setString(2, name);
            pst.setInt(3, age);
            pst.setString(4, position);
            pst.setInt(5, coach_id);
            pst.executeUpdate();
            show_staff_entity();
            JOptionPane.showMessageDialog(null, "Record Update Successful");
            jTextField_coach_id.setText("");
            jTextField_name.setText("");
            jTextField_age.setText("");
            jTextField_position.setText("");
            jTextField_staff_id.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_buttonGradient1_update1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int r = jTable1.getSelectedRow();
        String click = jTable1.getModel().getValueAt(r, 0).toString();
        int id = Integer.parseInt(click);
        String sqlquery = "Select * from staff where staff_id=" + id;
        try {
            pst = conn.prepareStatement(sqlquery);
            rs = pst.executeQuery();
            if (rs.next()) {
                
                String staff_id = rs.getString(1);
                jTextField_staff_id.setText(staff_id);
                
                String name = rs.getString(2);
                jTextField_name.setText(name);

                String age = rs.getString(3);
                jTextField_age.setText(age);
                
                String position = rs.getString(4);
                jTextField_position.setText(position);

                String coach_id = rs.getString(5);
                jTextField_coach_id.setText(coach_id);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField_positionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_positionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_positionActionPerformed

       public ArrayList<staff_entity> stafflist() {
        ArrayList<staff_entity> stafflist = new ArrayList<>();
        String sqlquery = " select * from staff where coach_id=1";
        try {
            Statement st = conn.createStatement();
            rs = st.executeQuery(sqlquery);
            staff_entity staff_entity;
            while (rs.next()) {
                staff_entity = new staff_entity(rs.getInt("staff_id"),rs.getString("name"),rs.getInt("age"),rs.getString("position"),rs.getInt("coach_id"));
                stafflist.add(staff_entity);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return stafflist;
    }

    public void show_staff_entity() {
        ArrayList<staff_entity> list = stafflist();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        Object[] row = new Object[11];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getStaff_id();
            row[1] = list.get(i).getName();
            row[2] = list.get(i).getAge();
            row[3] = list.get(i).getPosition();
            row[4] = list.get(i).getCoach_id();
            model.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.ButtonGradient buttonGradient1_add;
    private swing.ButtonGradient buttonGradient1_delete;
    private swing.ButtonGradient buttonGradient1_update1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_age;
    private javax.swing.JLabel jLabel_coach_id;
    private javax.swing.JLabel jLabel_name;
    private javax.swing.JLabel jLabel_position;
    private javax.swing.JLabel jLabel_staff_id;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_age;
    private javax.swing.JTextField jTextField_coach_id;
    private javax.swing.JTextField jTextField_name;
    private javax.swing.JTextField jTextField_position;
    private javax.swing.JTextField jTextField_staff_id;
    // End of variables declaration//GEN-END:variables
}
